name: tests

on:
  push:
    branches:
      - main
      - "*.x"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Bun.sh
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: ESLint
        run: bun run lint

      - name: Execute tests
        run: bun test

      - name: Run build
        run: bun run build
